[pytest]
addopts = -v -s --alluredir=allure-results
testpaths = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: быстрые проверки критического функционала
    regression: полный регрессионный прогон